---
title: "Informe Pedal Drive UP"
output: html_document
date: "2023-09-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

gc()
(rm(list = ls())) # limpiar las var del environment

# Lista de paquetes a utilizar
listofpackages <- c(
  "tidyverse", "lubridate", "readxl",
  "rstudioapi", "data.table", "corrplot",
  "tibble", "ggplot2", "DT", "plotly", "knitr",
  "janitor", "clipr", "skimr", "ggrepel", "factoextra",
  "corrplot", "ade4", "cluster", "stats",
  "cowplot", "rpart.plot",
  "rpart", "caret", "ROCR", "Metrics"
)

# revisar e instalar librerias que no es están instaladas
newPackages <- listofpackages[!(listofpackages %in% installed.packages()[, "Package"])]

if (length(newPackages)) install.packages(newPackages)
for (paquete in listofpackages) {
  suppressMessages(library(paquete, character.only = TRUE))
}

```

```{r funciones}

generar_boxplots_por_grupos <- function(df, var_interes, grupos = "cluster") {
  # Convertir a cuadro de datos
  df <- data.frame(df)

  # Definir etiquetas que con la cantidad de observaciones por grupos
  etiquetas <- paste(
    levels(factor(df[, grupos])), "\n(N = ", table(df[, grupos]), ")",
    sep = ""
  )

  # Generar gráfico
  boxplot <- ggplot(
    df,
    aes(
      x = factor(get(grupos)), y = get(var_interes),
      fill = factor(get(grupos))
    )
  ) +
    geom_boxplot() +
    theme(legend.position = "none") +
    scale_x_discrete(name = paste0(grupos), labels = etiquetas) +
    scale_y_continuous(name = paste0(var_interes)) +
    geom_hline(yintercept = median(df[, var_interes])) +
    theme(axis.text.x = element_text(size = rel(0.75)))

  return(boxplot)
}


generar_boxplots_por_grupos_2 <- function(df, var_interes, grupos = "Nivel_consumo") {
  # Convertir a cuadro de datos
  df <- data.frame(df)

  # Definir etiquetas que con la cantidad de observaciones por grupos
  etiquetas <- paste(
    levels(factor(df[, grupos])), "\n(N = ", table(df[, grupos]), ")",
    sep = ""
  )

  # Generar gráfico
  boxplot <- ggplot(
    df,
    aes(
      x = factor(get(grupos)), y = get(var_interes),
      fill = factor(get(grupos))
    )
  ) +
    geom_boxplot() +
    theme(legend.position = "none") +
    scale_x_discrete(name = paste0(grupos), labels = etiquetas) +
    scale_y_continuous(name = paste0(var_interes)) +
    geom_hline(yintercept = median(df[, var_interes])) +
    theme(axis.text.x = element_text(size = rel(0.75)))

  return(boxplot)
}


agrupamiento_km <- function(Fecha_hora) {
  for (i in c(1:length(Fecha_hora))) {
    if (is.na(Fecha_hora[i])) {
      Fecha_hora[i] <- Fecha_hora[i - 1]
    }
  }
  return(Fecha_hora)
}
```

```{r lectura de datos}
# LECTURA DE ARCHIVOS ------------------------------

path <- "C:/Users/REstevez/Documents/Conducción DriveUP/Datos Línea 41/"

files <- list.files(path, full.names = TRUE)

files_acelerador <- files[grepl("acelerador", files)]
files_velocidad <- files[grepl("velocidad", files)]
files_torque <- files[grepl("torque", files)]
files_empleados <- files[grepl("empleados", files)]
files_legajo <- files[grepl("legajo", files)]
files_rpm <- files[grepl("rpm", files)]
files_rpm_optimo <- files[grepl("rev", files)]
files_tiempos <- files[grepl("tiempos", files)]
files_freno <- files[grepl("freno", files)]
files_chasis_41 <- files[grepl("_chasis", files)]
files_consumo <- files[grepl("consumo", files)]
files_ralenti <- files[grepl("ralenti", files)]
files_combustible <- files[grepl("combustible", files)]
files_km <- files[grepl("km", files)]
files_chasis <- files[grepl("Tipos de", files)]
files_fichas <- files[grepl("Ficha -", files)]
files_sube <- files[grepl("Sube", files)]
files_diagramacion <- files[grepl("diagramacion", files)]

acelerador_41 <- fread(files_acelerador)
velocidad_41 <- fread(files_velocidad)
torque_41 <- fread(files_torque)
empleados_41 <- fread(files_empleados)
legajo_41 <- fread(files_legajo)
rpm_41 <- fread(files_rpm)
rpm_optimo_41 <- fread(files_rpm_optimo)
tiempos_41 <- fread(files_tiempos)
freno_41 <- fread(files_freno)
chasis_41 <- fread(files_chasis_41)
consumo_41 <- fread(files_consumo)
ralenti_41 <- fread(files_ralenti)
pbi_combustible <- fread(files_combustible) # fecha como POSIXct
pbi_km <- fread(files_km) # fecha como POSIXct
diagramacion <- fread(files_diagramacion)

# CHASIS -----------

chasis_41[, ficha := substr(ficha, 2, 5)]
chasis_41[, ficha := as.numeric(ficha)]

tipo_chasis <- read_xlsx(files_chasis) %>% 
  select(`Descripción del Vehículo`, `Tipo Combustible`) %>% 
  mutate(
    `Descripción del Vehículo` = as.character(`Descripción del Vehículo`)
  )

colnames(tipo_chasis) <- c("Chasis", "Combustible_chasis")

ficha_chasis <- fread(files_fichas)

ficha_chasis[,Ficha := substr(Ficha, 2, 5)]
ficha_chasis[,Ficha := as.numeric(Ficha)]
ficha_chasis[,Chasis := as.character(Chasis)]
ficha_chasis[Chasis == "BUS MB OF 1418-52303", Chasis := "BUS MB OF 1418-52"]
ficha_chasis[Chasis == "MB O500 1726-59", Chasis := "BUS MB O500 1726-59"]
ficha_chasis[Chasis == "MB OF 1721L-59", Chasis := "BUS MB OF 1721L-59"]
ficha_chasis[Chasis == "MB OH 1721-62", Chasis := "BUS MB OH 1721-62"]
ficha_chasis[Chasis == "MB OF 1722-59", Chasis := "BUS MB OF 1722-59"]
ficha_chasis <- ficha_chasis[!grepl("YT", Chasis),]

ficha_chasis <- left_join(ficha_chasis, tipo_chasis, by = c("Chasis" = "Chasis"))

```

```{r}
# PREPARACION DE DATOS ----------------------------

# LECTURA DE DATOS
datos_pca <- merge.data.table(consumo_41, acelerador_41,
  by = "cod_desig",
  all.x = TRUE
)
datos_pca <- merge.data.table(datos_pca, chasis_41,
  by = "cod_desig",
  all.x = TRUE
)
datos_pca <- merge.data.table(datos_pca, empleados_41,
  by = "cod_desig",
  all.x = TRUE
)
datos_pca <- merge.data.table(datos_pca, freno_41,
  by = "cod_desig",
  all.x = TRUE
)
datos_pca <- merge.data.table(datos_pca, ralenti_41,
  by = "cod_desig",
  all.x = TRUE
)
datos_pca <- merge.data.table(datos_pca, rpm_41,
  by = "cod_desig",
  all.x = TRUE
)
datos_pca <- merge.data.table(datos_pca, rpm_optimo_41,
  by = "cod_desig",
  all.x = TRUE
)
datos_pca <- merge.data.table(datos_pca, tiempos_41,
  by = "cod_desig",
  all.x = TRUE
)
datos_pca <- merge.data.table(datos_pca, torque_41,
  by = "cod_desig",
  all.x = TRUE
)
datos_pca <- merge.data.table(datos_pca, velocidad_41,
  by = "cod_desig",
  all.x = TRUE
)

# ETL
setnames(datos_pca, colnames(datos_pca), gsub("Suma de ", "", colnames(datos_pca)))
setnames(datos_pca, colnames(datos_pca), gsub("profile", "", colnames(datos_pca)))

datos_pca <- datos_pca[, -c("Aceleradorprom", "Empleado", "Tipo dia", "Linea 1", "% Frenadas bruscas")]

variables_rpm <- colnames(datos_pca)[grepl("rpm", colnames(datos_pca), ignore.case = TRUE)]
variables_acelerador <- colnames(datos_pca)[grepl("accel", colnames(datos_pca), ignore.case = TRUE)]
variables_torque <- colnames(datos_pca)[grepl("torque", colnames(datos_pca), ignore.case = TRUE)]
variables_freno <- colnames(datos_pca)[grepl("brake", colnames(datos_pca), ignore.case = TRUE)]
variables_consumo <- colnames(datos_pca)[grepl("consump", colnames(datos_pca), ignore.case = TRUE)]
variables_consumo <- variables_consumo[-3]
variables_ralenti <- colnames(datos_pca)[grepl("ralenti", colnames(datos_pca), ignore.case = TRUE)]
variables_velocidad <- colnames(datos_pca)[grepl("speed", colnames(datos_pca), ignore.case = TRUE)]
variables_tiempo <- colnames(datos_pca)[grepl("times", colnames(datos_pca), ignore.case = TRUE)]

lista_variables <- list()

lista_variables[["rpm"]] <- variables_rpm
lista_variables[["acelerador"]] <- variables_acelerador
lista_variables[["torque"]] <- variables_torque
lista_variables[["freno"]] <- variables_freno
lista_variables[["consumo"]] <- variables_consumo
lista_variables[["ralenti"]] <- variables_ralenti
lista_variables[["velocidad"]] <- variables_velocidad
lista_variables[["tiempos"]] <- variables_tiempo

etiquetas_consumo <- c("Bajo", "Medio", "Alto")

datos_pca[, Nivel_consumo := cut(consumption.avgFuel,
  breaks = quantile(consumption.avgFuel, probs = c(0, 0.25, 0.75, 1)),
  labels = etiquetas_consumo,
  include.lowest = TRUE
), by = Chasis]

datos_pca[, ficha := substr(ficha, 2, 5)]
datos_pca[, ficha := as.numeric(ficha)]
# datos_pca[, Nivel_consumo := as.numeric(Nivel_consumo)]



datos_pca_agrale <- datos_pca[Chasis == "BUS AGRALE MT 17.0/LE", ]
datos_pca_agrale <- datos_pca_agrale[Distance > 30, ]
datos_pca_agrale <- datos_pca_agrale[consumption.avgFuel > 15, ]
datos_pca_agrale <- datos_pca_agrale[!is.na(cod_empleado)]
datos_pca_agrale_2 <- datos_pca_agrale
Nivel_consumo_agrale <- datos_pca_agrale[, "Nivel_consumo"]
datos_pca_agrale <- datos_pca_agrale[, -c("Chasis", "Nivel_consumo", "cod_empleado", "Fecha", "cod_desig")]
var_agrale <- skim(datos_pca_agrale)[c(2, 7, 11)]
setDT(var_agrale)
var_agrale <- unlist(var_agrale[numeric.p0 == numeric.p100, "skim_variable"])
var_agrale <- as.vector(var_agrale)
datos_pca_agrale <- datos_pca_agrale[, -..var_agrale]
datos_pca_agrale <- as.data.frame(scale(datos_pca_agrale))
datos_pca_agrale$Nivel_consumo <- as.data.frame(Nivel_consumo_agrale)
datos_pca_agrale <- as.data.table(datos_pca_agrale)


datos_pca_mb <- datos_pca[Chasis == "MB O500U 1826-59", ]
datos_pca_mb <- datos_pca_mb[Distance > 30, ]
datos_pca_mb <- datos_pca_mb[consumption.avgFuel > 15, ]
datos_pca_mb <- datos_pca_mb[!is.na(cod_empleado)]
datos_pca_mb_2 <- datos_pca_mb
Nivel_consumo_mb <- datos_pca_mb[, "Nivel_consumo"]
datos_pca_mb <- datos_pca_mb[, -c("Chasis", "Nivel_consumo", "cod_empleado", "Fecha", "cod_desig")]
var_mb <- skim(datos_pca_mb)[c(2, 7, 11)]
setDT(var_mb)
var_mb <- unlist(var_mb[numeric.p0 == numeric.p100, "skim_variable"])
var_mb <- as.vector(var_mb)
datos_pca_mb <- datos_pca_mb[, -..var_mb]
datos_pca_mb <- as.data.frame(scale(datos_pca_mb))
datos_pca_mb$Nivel_consumo <- as.data.frame(Nivel_consumo_mb)
datos_pca_mb <- as.data.table(datos_pca_mb)

datos_cluster_agrale <- datos_pca_agrale[, -c("ficha", "cod_emp", "Mes")]

datos_cluster_mb <- datos_pca_mb[, -c("ficha", "cod_emp", "Mes")]

vars_to_cluster <- c(
  "consumption.avgFuel", "consumption.fuel", "accelerator.get80",
  "Speed.speedAvg", "Torque.torqueAvg", "rpm.optimalRangePercentage",
  "times.engine", "brakeApplication", "Distance"
)


dt_cluster_agrale <- scale(datos_cluster_agrale[, -c("Nivel_consumo")])
dt_cluster_agrale <- as.data.frame(dt_cluster_agrale)
setDT(dt_cluster_agrale)
dt_cluster_agrale$Nivel_consumo <- datos_cluster_agrale[, c("Nivel_consumo")]

dt_cluster_mb <- scale(datos_cluster_mb[-370, -c("Nivel_consumo")])
dt_cluster_mb <- as.data.frame(dt_cluster_mb)
setDT(dt_cluster_mb)
dt_cluster_mb$Nivel_consumo <- datos_cluster_mb[-370, c("Nivel_consumo")] 
```


```{r}
consumo_ficha_fecha <- merge.data.table(chasis_41, consumo_41,
  by = "cod_desig",
  all.x = TRUE
)
consumo_ficha_fecha <- merge.data.table(consumo_ficha_fecha, empleados_41,
  by = "cod_desig",
  all.x = TRUE
)
consumo_ficha_fecha <- merge.data.table(consumo_ficha_fecha, tiempos_41,
  by = "cod_desig",
  all.x = TRUE
)
consumo_ficha_fecha <- merge.data.table(consumo_ficha_fecha, acelerador_41,
  by = "cod_desig",
  all.x = TRUE
)
consumo_ficha_fecha <- merge.data.table(consumo_ficha_fecha, torque_41,
  by = "cod_desig",
  all.x = TRUE
)

# consumo_ficha_fecha <- consumo_ficha_fecha[ficha == "F3495",]
setnames(consumo_ficha_fecha, colnames(consumo_ficha_fecha), gsub("Suma de ", "", colnames(consumo_ficha_fecha)))


consumo_ficha_fecha <- consumo_ficha_fecha[!is.na(accelerator.get80), ]

consumo_agrupados_ff <- consumo_ficha_fecha[, .(
  KM_DUP = sum(Distance, na.rm = TRUE),
  LTS_DUP = sum(consumption.fuel, na.rm = TRUE),
  Acelerador = weighted.mean(accelerator.get80, times.driving, na.rm = TRUE),
  Tiempo = sum(times.driving, na.rm = TRUE),
  cant_servicios = .N
), by = .(ficha, Fecha)]

consumo_agrupados_ff[, `:=`(
  Consumo_DUP = LTS_DUP / KM_DUP * 100,
  Fecha = as.Date(Fecha),
  Velocidad_DUP = (KM_DUP / Tiempo) * 60 * 60
)]

consumo_agrupados_ff <- consumo_agrupados_ff[KM_DUP > 45, ]
consumo_agrupados_ff <- consumo_agrupados_ff[KM_DUP < 300, ]
consumo_agrupados_ff <- consumo_agrupados_ff[!is.na(Acelerador), ]
consumo_agrupados_ff <- consumo_agrupados_ff[Velocidad_DUP < 40, ]

#consumo_agrupados_ff <- consumo_agrupados_ff[Distancia > 50, ]
#consumo_agrupados_ff <- consumo_agrupados_ff[Consumo_DUP > 20, ]

# consumo_ff <- merge.data.table(pbi_consumo_fecha, consumo_agrupados_ff,
#                                by.x = c("Ficha", "Fecha"),
#                                by.y = c("ficha", "Fecha"),
#                                all.x = TRUE
#                                )

consumo_ff <- merge.data.table(consumo_agrupados_ff, ficha_chasis,
                               by.x = c("ficha"),
                               by.y = c("Ficha"),
                               all.x = TRUE
                               )

# consumo_fecha <- consumo_ff[, .(
#   KM_DUP = sum(KM_DUP, na.rm = TRUE),
#   LTS_DUP = sum(LTS_DUP, na.rm = TRUE),
#   Acelerador = weighted.mean(Acelerador, Tiempo, na.rm = TRUE),
#   Tiempo = sum(Tiempo, na.rm = TRUE),
#   KM_PBI = sum(KM_PBI, na.rm = TRUE),
#   LTS_PBI = sum(LTS_PBI, na.rm = TRUE)
# ), by = .(Ficha)]
# 
consumo_ff[, `:=`(
  Consumo_DUP = LTS_DUP / KM_DUP * 100
  #Consumo_PBI = LTS_PBI / KM_PBI * 100
)]
# 
# consumo_fecha[, `:=`(
#   Consumo_DUP = LTS_DUP / KM_DUP * 100,
#   Consumo_PBI = LTS_PBI / KM_PBI * 100
# )]
# 
# consumo_fecha[, `:=`(
#   relacion_consumo = Consumo_DUP / Consumo_PBI - 1
# )]
# 
# consumo_ff[, `:=`(
#   relacion_consumo = Consumo_DUP / Consumo_PBI - 1
# )]


#consumo_ff <- consumo_ff[Distancia_DUP > 0, ]
#consumo_ff <- consumo_ff[LTS_DUP > 0, ]
#consumo_ff <- consumo_ff[KM_pbi > 0, ]



#consumo_ff[is.infinite(Consumo_PBI), Consumo_PBI := NA]
consumo_ff[is.infinite(Consumo_DUP), Consumo_DUP := NA]


#ggplotly(
#  ggplot(subset(consumo_ficha_fecha, ficha == "F3495")) +
#    aes(x = Acelerador, y = Consumo_DUP) +
#    geom_point() +
#    facet_grid(~Chasis)
#)

#ggplotly(
#  ggplot(subset(consumo_ficha_fecha, ficha == "F3495")) +
#    aes(x = Acelerador, y = get("l/100km")) +
#    geom_point() +
#    facet_grid(~Chasis)
#)

#ggplotly(
#  ggplot(subset(consumo_ficha_fecha, ficha == "F3495")) +
#    geom_point(aes(x = Acelerador, y = get("l/100km")), color = "blue") +
#    geom_point(aes(x = Acelerador, y = Consumo_DUP), color = "red")
#)



```



```{r}
pbi_combustible <- pbi_combustible[CodAlmacen == "CAR", ]
pbi_combustible[, hs_entre_cargas := gsub(",", ".", `Hs entre cargas`)]
pbi_combustible[, hs_entre_cargas := as.numeric(hs_entre_cargas)]
pbi_combustible <- pbi_combustible[, -"Hs entre cargas"]
pbi_combustible[, Ficha := substr(Ficha, 2, 5)]
pbi_combustible[, Ficha := as.numeric(Ficha)]
pbi_combustible[, FechaCorregida := as.Date(FechaCorregida)]
pbi_km[, Ficha := substr(Ficha, 2, 5)]
pbi_km[, Ficha := as.numeric(Ficha)]
pbi_km[, Fecha := as.Date(Fecha)]
pbi_km <- pbi_km[Chasis != "BUS MB OH 1618-55",]




#consumo_ff <- consumo_ff[KM_PBI > 0, ]


pbi_combustible <- merge.data.table(pbi_combustible, ficha_chasis[,c("Ficha", "Combustible_chasis")],
                         by.x = "Ficha",
                         by.y ="Ficha",
                         all.x = TRUE)

setorder(pbi_combustible, Ficha, FechaCorregida, `Fecha Hora consumo`)

pbi_combustible[, `:=`(
  Horas_prox_carga = (shift(`Fecha Hora consumo`, type = "lead") - `Fecha Hora consumo`)/3600
),
by = "Ficha"
]

pbi_combustible[is.na(Horas_prox_carga), 
  Horas_prox_carga := 0]


pbi_combustible[, `:=`(
  Taller_prox = lead(CodAlmacen, default = ""),
  Taller_ant = lag(CodAlmacen, default = ""),
  Proxima_carga = lead(ConsumoTotal, default = 0),
  Carga_anterior = lag(ConsumoTotal, default = 0),
  #Mismo_combustible = ProductName == Combustible_chasis,
  Mismo_combustible = TRUE,
  Proximo_combustible = lead(ProductName, default = "") == ProductName,
  Combustible_anterior = lag(ProductName, default = "") == ProductName
),
by = "Ficha"
]

pbi_combustible[, `:=`(
  Cargas_en_1_hr_anterior =
    hs_entre_cargas < 1.5 & hs_entre_cargas > 0 &
      ConsumoTotal > 40 & Carga_anterior > 40 &
      CodAlmacen == Taller_ant,
  Cargas_en_1_hr_prox =
    Horas_prox_carga < 1.5 & Horas_prox_carga > 0 &
      ConsumoTotal > 40 & Proxima_carga > 40 &
      CodAlmacen == Taller_prox
),
by = "Ficha"
]

pbi_combustible[, `:=`(
  Cargas_en_1_hr_anterior = coalesce(Cargas_en_1_hr_anterior, FALSE),
  Cargas_en_1_hr_prox = coalesce(Cargas_en_1_hr_prox, FALSE)
),
by = "Ficha"
]

pbi_combustible[, `:=`(
  Cargas_en_1_hr = Cargas_en_1_hr_prox | Cargas_en_1_hr_anterior
),
by = "Ficha"
]

pbi_combustible[, `:=`(
  chequeo_cruzado = Cargas_en_1_hr_anterior & Combustible_anterior |
    Cargas_en_1_hr_prox & Proximo_combustible,
  Cargas_mismo_dia =
    hs_entre_cargas < 6 & hs_entre_cargas > 0 &
      CodAlmacen != Taller_ant |
      Horas_prox_carga < 2 & Horas_prox_carga > 0 &
        CodAlmacen != Taller_prox
),
by = "Ficha"
]

pbi_combustible[, `:=`(
  Cargas_mismo_dia = coalesce(Cargas_mismo_dia, FALSE)
),
by = "Ficha"
]

pbi_combustible[, `:=`(
 ConsumoTotal = if_else(Cargas_en_1_hr & !Mismo_combustible, 0, ConsumoTotal)
 ),
by = "Ficha"
]

cruzado <- pbi_combustible[chequeo_cruzado == TRUE, c("Ficha", "Fecha Hora consumo")]
cruzado$Filtrar <- TRUE

pbi_combustible <- pbi_combustible[chequeo_cruzado < 1, chequeo_cruzado := Cargas_en_1_hr & !Mismo_combustible] 

cruzado_2 <- pbi_combustible[chequeo_cruzado == TRUE, c("Ficha", "Fecha Hora consumo")]
cruzado_2$Filtrar <- TRUE

cruzado <- rbind(cruzado, cruzado_2)
cruzado$Filtrar <- TRUE

pbi_consumo <- merge.data.table(pbi_combustible, pbi_km,
  by.x = c("Ficha", "FechaCorregida"),
  by.y = c("Ficha", "Fecha"),
  all = TRUE
)

duplicados <- pbi_consumo[duplicated(pbi_consumo[, c("Ficha", "hs_entre_cargas", "Km", "FechaCorregida")]), ]

if (nrow(duplicados) > 0) {
  for (i in c(1:nrow(duplicados))) {
    pbi_consumo[Ficha == duplicados$Ficha[i] &
      FechaCorregida == duplicados$FechaCorregida[i], hs_entre_cargas := 0]
  }
}

pbi_consumo[duplicated(pbi_consumo[, c("Ficha", "Km", "FechaCorregida")]), Km := 0]
pbi_consumo[(hs_entre_cargas == 0 & Texto != "M" & !is.na(hs_entre_cargas)), ]
pbi_consumo <- pbi_consumo[!is.na(Chasis), ]

setorder(pbi_consumo, Ficha, -FechaCorregida, -`Fecha Hora consumo`)

pbi_consumo <- merge.data.table(pbi_consumo, consumo_agrupados_ff,
                       all = TRUE,
                       by.x = c("Ficha", "FechaCorregida"),
                       by.y = c("ficha", "Fecha"))

#setnames(pbi_consumo, "FechaCorregida", "Fecha")

pbi_consumo[, Fecha_hora := agrupamiento_km(`Fecha Hora consumo`), by = "Ficha"]

setorder(pbi_consumo, Ficha, FechaCorregida, Fecha_hora)

pbi_consumo <- pbi_consumo[!is.na(Fecha_hora),]

pbi_consumo[!is.na(Texto) & Texto == "M", `Fecha Hora consumo` := `Fecha Hora consumo` + 12*60*60]
pbi_consumo[, Fecha := as.Date(Fecha_hora)]
pbi_consumo[, Hora := lubridate::hour(Fecha_hora)]
pbi_consumo[Hora < 6, Fecha := Fecha - 1]

pbi_consumo <- merge.data.table(pbi_consumo, cruzado,
                   by.x = c("Ficha", "Fecha_hora"),
                   by.y = c("Ficha", "Fecha Hora consumo"),
                   all.x = TRUE)

pbi_consumo[is.na(Filtrar), Filtrar := FALSE]

pbi_consumo_filtrado <- pbi_consumo[Filtrar == FALSE,]
pbi_consumo_filtrado <- pbi_consumo_filtrado[,Filtrar := NULL]

pbi_consumo_hora <- pbi_consumo_filtrado[,.(
  Almacen = first(sort(CodAlmacen)),
  LTS = sum(ConsumoTotal, na.rm = TRUE),
  KM = sum(Km, na.rm = TRUE),
  Combustible = first(sort(ProductName)),
  Texto = first(sort(Texto)),
  KM_DUP = sum(KM_DUP, na.rm = TRUE),
  LTS_DUP = sum(LTS_DUP, na.rm = TRUE),
  Acelerador = weighted.mean(Acelerador, Tiempo, na.rm = TRUE),
  Tiempo = sum(Tiempo, na.rm = TRUE),
  cant_servicios = .N
  ),
  by = .(Ficha, Fecha_hora, Chasis)]

#pbi_consumo_hora <- pbi_consumo_hora[KM_DUP > 0,]

pbi_consumo_hora <- pbi_consumo_hora[Almacen == "CAR",]

pbi_consumo_hora[Texto == "M", Fecha_hora := Fecha_hora + 12*60*60]
pbi_consumo_hora[, Hora := hour(Fecha_hora)]
pbi_consumo_hora[, Fecha := as.Date(Fecha_hora)]
pbi_consumo_hora[Hora < 6, Fecha := Fecha - 1]

pbi_consumo_fecha <- pbi_consumo_hora[, .(Cantidad_cargas = .N,
LTS_PBI = sum(LTS, na.rm = TRUE),
KM_PBI = sum(KM, na.rm = TRUE),
KM_DUP = sum(KM_DUP, na.rm = TRUE),
LTS_DUP = sum(LTS_DUP, na.rm = TRUE),
Acelerador = weighted.mean(Acelerador, Tiempo, na.rm = TRUE),
Tiempo = sum(Tiempo, na.rm = TRUE)
),
by = .(Ficha, Fecha, Chasis)
]
pbi_consumo_fecha <- pbi_consumo_fecha[, .SD[-1], by = Ficha]

pbi_consumo_ficha <- pbi_consumo_hora[, .(Cantidad_cargas = .N,
LTS_PBI = sum(LTS, na.rm = TRUE),
KM_PBI = sum(KM, na.rm = TRUE),
KM_DUP = sum(KM_DUP, na.rm = TRUE),
LTS_DUP = sum(LTS_DUP, na.rm = TRUE),
Acelerador = weighted.mean(Acelerador, Tiempo, na.rm = TRUE),
Tiempo = sum(Tiempo, na.rm = TRUE)
),
by = .(Ficha, Chasis)]

pbi_consumo_fecha[, Consumo_PBI := round(LTS_PBI / KM_PBI * 100, 2)]
pbi_consumo_fecha[, Consumo_DUP := round(LTS_DUP / KM_DUP * 100, 2)]
pbi_consumo_fecha[, Consumo_combinado := round(LTS_PBI / KM_DUP * 100, 2)]
pbi_consumo_fecha[is.infinite(Consumo_PBI), Consumo_PBI := NA]
pbi_consumo_fecha[is.infinite(Consumo_DUP), Consumo_DUP := NA]
pbi_consumo_fecha[is.infinite(Consumo_combinado), Consumo_combinado := NA]

pbi_consumo_ficha[, Consumo_PBI := round(LTS_PBI / KM_PBI * 100, 2)]
pbi_consumo_ficha[, Consumo_DUP := round(LTS_DUP / KM_DUP * 100, 2)]
pbi_consumo_ficha[, Consumo_combinado := round(LTS_PBI / KM_DUP * 100, 2)]
pbi_consumo_ficha[is.infinite(Consumo_PBI), Consumo_PBI := NA]
pbi_consumo_ficha[is.infinite(Consumo_DUP), Consumo_DUP := NA]
pbi_consumo_ficha[is.infinite(Consumo_combinado), Consumo_combinado := NA]


pbi_consumo_fecha <- pbi_consumo_fecha[!is.na(Acelerador),]
pbi_consumo_ficha <- pbi_consumo_ficha[!is.na(Acelerador),]

etiquetas_consumo <- c("Bajo", "Medio", "Alto")


pbi_consumo_fecha[, Nivel_consumo_PBI := .bincode(Consumo_PBI,
  breaks = quantile(Consumo_PBI, probs = c(0, 0.20, 0.80, 1), na.rm = TRUE),
  #labels = etiquetas_consumo,
  include.lowest = TRUE
), by = Chasis]

pbi_consumo_fecha[, Nivel_consumo_DUP := .bincode(Consumo_DUP,
  breaks = quantile(Consumo_DUP, probs = c(0, 0.20, 0.80, 1), na.rm = TRUE),
  #labels = etiquetas_consumo,
  include.lowest = TRUE
), by = Chasis]

pbi_consumo_fecha[, Nivel_consumo_combinado := .bincode(Consumo_combinado,
  breaks = quantile(Consumo_combinado, probs = c(0, 0.20, 0.80, 1), na.rm = TRUE),
  #labels = etiquetas_consumo,
  include.lowest = TRUE
), by = Chasis]

pbi_consumo_fecha[, Nivel_consumo_PBI := factor(Nivel_consumo_PBI,
                                           levels = c(1,2,3),
                                           labels = etiquetas_consumo)]

pbi_consumo_fecha[, Nivel_consumo_DUP := factor(Nivel_consumo_DUP,
                                           levels = c(1,2,3),
                                           labels = etiquetas_consumo)]

pbi_consumo_fecha[, Nivel_consumo_combinado := factor(Nivel_consumo_combinado,
                                           levels = c(1,2,3),
                                           labels = etiquetas_consumo)]
```



```{r}

  ggplot(pbi_consumo_fecha) +
    aes(x = Nivel_consumo_DUP, y = Acelerador, fill = Nivel_consumo_DUP) +
    geom_boxplot(alpha = 0.7) +
    facet_grid(~Chasis) +
  theme_minimal() +
  labs(title = "Porcentaje del acelerador por nivel de consumo del DUP") +
  scale_y_continuous(labels = seq(0,70,10), breaks = seq(0,70,10)) +
  scale_fill_manual(values = c("Bajo" = "green", 
                               "Medio" = "yellow", 
                               "Alto" = "red"))+
  theme(
    plot.title = element_text(hjus = 0.5),
    legend.position = "none"
  )


```

```{r}
ggplot(subset(consumo_ff, Nivel_consumo_DUP != "Medio")) +
  aes(x = Nivel_consumo_DUP, y = Acelerador) +
  geom_boxplot() +
  facet_grid(~Chasis) +
  labs(
    title = "Acelerador en función del consumo",
    subtitle = "30% de choferes con consumo más alto vs. el 30% con consumo más bajo",
    x = "Nivel Consumo",
    y = "Porcentaje acelerador a +80%"
  ) +
  theme(
    plot.title = element_text(hjus = 0.5, size = 36),
    plot.subtitle = element_text(hjus = 0.5, size = 18),
    axis.title.x = element_text(size = 21),
    axis.title.y = element_text(size = 21),
    axis.text.x = element_text(size = 18),
    axis.text.y = element_text(size = 18),
    strip.text = element_text(size = 18)
  )
```



```{r}

ggplot(subset(consumo_ff, Nivel_consumo_PBI != "Medio")) +
  aes(x = Nivel_consumo_PBI, y = Acelerador) +
  geom_boxplot() +
  facet_grid(~Chasis) +
  labs(
    title = "Acelerador en función del consumo",
    subtitle = "30% de choferes con consumo más alto vs. el 30% con consumo más bajo",
    x = "Nivel Consumo",
    y = "Porcentaje acelerador a +80%"
  ) +
  theme(
    plot.title = element_text(hjus = 0.5, size = 36),
    plot.subtitle = element_text(hjus = 0.5, size = 18),
    axis.title.x = element_text(size = 21),
    axis.title.y = element_text(size = 21),
    axis.text.x = element_text(size = 18),
    axis.text.y = element_text(size = 18),
    strip.text = element_text(size = 18)
  )
```


```{r}
ggplotly(
  ggplot(pbi_consumo_fecha) +
    aes(x = LTS_DUP, y = LTS_PBI) +
    geom_point() +
    geom_smooth(method = "lm") +
    facet_grid(~Chasis) +
    coord_fixed()
)
```

```{r}
ggplotly(
  ggplot(pbi_consumo_fecha) +
    aes(x = KM_DUP, y = KM_PBI) +
    geom_point() +
    geom_smooth(method = "lm") +
    facet_grid(~Chasis) +
    coord_fixed()
)
```




```{r}

ggplotly(
  ggplot(pbi_consumo_fecha) +
    aes(x = Consumo_combinado, y = Consumo_PBI) +
    geom_point() +
    geom_smooth(method = "lm") +
    facet_grid(~Chasis)
)
```


```{r}
diagramacion <- fread(files_diagramacion, dec = ",")
diagramacion[, Fecha := dmy(Fecha)]
diagramacion[, Sale := as.numeric(Fecha) + SaleUnidad]
diagramacion[, Sale := openxlsx::convertToDateTime(diagramacion$Sale, origin = "1970-01-01")]
diagramacion[, Llega := as.numeric(Fecha) + LlegaUnidad]
diagramacion[, Llega := openxlsx::convertToDateTime(diagramacion$Llega, origin = "1970-01-01")]
diagramacion[, Llega := if_else(Llega <= Sale, Llega + 1, Llega)]
diagramacion[, Hora_llega := hour(Llega)]

ggplotly(
ggplot(diagramacion) +
  aes(x = Hora_llega) +
  geom_bar(stat = "count")
)

ggplotly(
ggplot(pbi_combustible) +
  aes(x = hour(`Fecha Hora consumo`)) +
  geom_bar(stat = "count")
)
```


```{r}
diagramacion_2 <- diagramacion[Llega > Sale,]
a_filtrar <- diagramacion_2[, c("Fecha", "Ficha")]

a_analizar <- merge.data.table(a_filtrar, consumo_ff, by.x = c("Ficha", "Fecha"), by.y = c("Ficha", "Fecha"))

```

```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
library(alr4)
library(ISLR)
library(GGally)
library(car)
library(cowplot)
library(fastDummies)


lm_consumos <- consumo_ff[,-c("Nivel_consumo_DUP", "Nivel_consumo_PBI", "relacion_consumo",
                              "Ficha", "Fecha", "Consumo_PBI", "relacion_consumo")]
lm_consumos <- fastDummies::dummy_cols(lm_consumos)

modelo <- lm(Consumo_DUP~. , data = lm_consumos)
summary(modelo)

```

```{r}

lm_consumos_2 <- consumo_ff[,-c("Nivel_consumo_DUP", "Nivel_consumo_PBI", "relacion_consumo",
                              "Ficha", "Fecha", "relacion_consumo", "Consumo_PBI",
                              "LTS_PBI", "KM_PBI", "cant_servicios")]
lm_consumos_2 <- fastDummies::dummy_cols(lm_consumos_2)

modelo_3 <- lm(Consumo_DUP~. , data = lm_consumos_2)
summary(modelo_3)

```

```{r}
consumo_ficha_fecha_2 <- consumo_ficha_fecha[consumption.avgFuel > 20 & consumption.avgFuel < 100,]

lm_consumos_3 <- consumo_ficha_fecha_2[,-c("Linea 1", "Tipo dia", "Empleado", "ficha", "cod_emp",
                                         "Fecha", "Aceleradorprom", "consumption.fuel",
                                         "accelerator.get1", "accelerator.get20", "accelerator.get40",
                                         "accelerator.get60", "Mes", "cod_desig",
                                         "profileTorque.get1", "profileTorque.get10", "profileTorque.get100",
                                         "profileTorque.get20", "profileTorque.get30", "profileTorque.get40",
                                         "profileTorque.get50", "profileTorque.get60", "profileTorque.get70",
                                         "profileTorque.get80", "profileTorque.get90")]
lm_consumos_3 <- fastDummies::dummy_cols(lm_consumos_3)
lm_consumos_3 <- lm_consumos_3[,-c("Chasis")]
lm_consumos_3 <- lm_consumos_3 %>%
    mutate_if(is.numeric, scale)

modelo_4 <- lm(consumption.avgFuel~., data = lm_consumos_3)
summary(modelo_4)
```

```{r}
ggplot(lm_consumos_3)+aes(y = profileTorque.torqueAvg)+geom_boxplot()
ggplot(lm_consumos_3)+aes(y = accelerator.get80)+geom_boxplot()
```

